"""PyMOL PSE/PML generation."""

import os
import numpy as np


class PyMOLVisualizer:
    """Generate PyMOL session and script files."""

    def create_pml_script(self, base_path, output_pml):
        """Generate a PML script that loads all outputs and creates visualization."""
        prefix = os.path.basename(base_path)
        dirpath = os.path.dirname(base_path)

        lines = [
            "# IW-ENM Visualization Script",
            "# Generated by iw_enm package",
            "",
            "bg_color white",
            "set ray_shadow, 0",
            "",
            f'# Load equilibrium structure',
            f'load {prefix}_equilibrium.pdb, equilibrium',
            'show cartoon, equilibrium',
            'color gray70, equilibrium',
            'set cartoon_transparency, 0.5, equilibrium',
            '',
            f'# Load trajectory',
            f'load {prefix}_trajectory.pdb, trajectory',
            'show spheres, trajectory',
            'set sphere_scale, 0.4, trajectory',
            'spectrum b, blue_white_red, trajectory',
            '',
            f'# Load initial spring network',
            f'load {prefix}_springs_t0.pdb, springs_t0',
            'show sticks, springs_t0',
            'set stick_radius, 0.05, springs_t0',
            'spectrum b, green_yellow_red, springs_t0',
            'hide everything, springs_t0',
            '',
            f'# Load final spring network',
            f'load {prefix}_springs_final.pdb, springs_final',
            'show sticks, springs_final',
            'set stick_radius, 0.05, springs_final',
            'spectrum b, green_yellow_red, springs_final',
            'hide everything, springs_final',
            '',
            f'# Load velocity vectors',
            f'load {prefix}_velocities_t0.pdb, velocities',
            'show sticks, velocities',
            'set stick_radius, 0.08, velocities',
            'color cyan, velocities',
            'hide everything, velocities',
            '',
            f'# Load force vectors',
            f'load {prefix}_forces_final.pdb, forces',
            'show sticks, forces',
            'set stick_radius, 0.08, forces',
            'color red, forces',
            'hide everything, forces',
            '',
            '# Default view: trajectory + equilibrium',
            'show cartoon, equilibrium',
            'show spheres, trajectory',
            '',
            '# Color trajectory by RMSF (b-factor)',
            'spectrum b, blue_white_red, trajectory',
            '',
            '# Groups',
            'group network, springs_t0 springs_final',
            'group vectors, velocities forces',
            '',
            '# Animation settings',
            'set movie_loop, 1',
            'set movie_fps, 15',
            '',
            'zoom trajectory',
            'orient',
        ]

        with open(output_pml, "w") as f:
            f.write("\n".join(lines) + "\n")

    def create_session(self, base_path, output_pse, trajectory, spring_networks,
                       forces_history, velocities_history, structure, rmsf=None):
        """
        Create PyMOL PSE session file.
        Requires pymol to be importable.
        """
        try:
            import pymol
            from pymol import cmd
        except ImportError:
            print("pymol not available, generating PML script only.")
            pml_path = output_pse.replace(".pse", ".pml")
            self.create_pml_script(base_path, pml_path)
            return pml_path

        pymol.finish_launching(["pymol", "-cq"])
        cmd.reinitialize()

        prefix = os.path.basename(base_path)
        dirpath = os.path.dirname(base_path)

        # Load files
        eq_pdb = f"{base_path}_equilibrium.pdb"
        traj_pdb = f"{base_path}_trajectory.pdb"
        springs_t0 = f"{base_path}_springs_t0.pdb"
        springs_final = f"{base_path}_springs_final.pdb"
        vel_pdb = f"{base_path}_velocities_t0.pdb"
        forces_pdb = f"{base_path}_forces_final.pdb"

        if os.path.exists(eq_pdb):
            cmd.load(eq_pdb, "equilibrium")
            cmd.show("cartoon", "equilibrium")
            cmd.color("gray70", "equilibrium")
            cmd.set("cartoon_transparency", 0.5, "equilibrium")

        if os.path.exists(traj_pdb):
            cmd.load(traj_pdb, "trajectory")
            cmd.show("spheres", "trajectory")
            cmd.set("sphere_scale", 0.4, "trajectory")

            # Color by RMSF if available
            if rmsf is not None:
                for state in range(1, cmd.count_states("trajectory") + 1):
                    for i, val in enumerate(rmsf):
                        cmd.alter(
                            f"trajectory and id {i+1} and state {state}",
                            f"b={val:.3f}"
                        )
                cmd.spectrum("b", "blue_white_red", "trajectory")

        if os.path.exists(springs_t0):
            cmd.load(springs_t0, "springs_t0")
            cmd.show("sticks", "springs_t0")
            cmd.set("stick_radius", 0.05, "springs_t0")
            cmd.spectrum("b", "green_yellow_red", "springs_t0")

        if os.path.exists(springs_final):
            cmd.load(springs_final, "springs_final")
            cmd.show("sticks", "springs_final")
            cmd.set("stick_radius", 0.05, "springs_final")
            cmd.spectrum("b", "green_yellow_red", "springs_final")
            cmd.disable("springs_final")

        if os.path.exists(vel_pdb):
            cmd.load(vel_pdb, "velocities")
            cmd.show("sticks", "velocities")
            cmd.set("stick_radius", 0.08, "velocities")
            cmd.color("cyan", "velocities")
            cmd.disable("velocities")

        if os.path.exists(forces_pdb):
            cmd.load(forces_pdb, "forces")
            cmd.show("sticks", "forces")
            cmd.set("stick_radius", 0.08, "forces")
            cmd.color("red", "forces")
            cmd.disable("forces")

        cmd.bg_color("white")
        cmd.set("ray_shadow", 0)
        cmd.set("movie_loop", 1)
        cmd.set("movie_fps", 15)
        cmd.zoom("trajectory")
        cmd.orient()

        cmd.save(output_pse)
        cmd.quit()
        print(f"PyMOL session saved: {output_pse}")
        return output_pse
